### PR TITLE
fix: linting errors

### LINKED ISSUE #6: Resolve linter issues and move lint workflow to the PR/push
Check out the issues found under:
https://github.com/WirelessCar/nauth/actions/workflows/lint.yml

or simply run
```
golangci-lint run
```
locally. (part of mise setup)

Get rid of the linting errors so that the workflow can be incorporated in our development workflow.

### PR DESCRIPTION
**Pull request by aKjeller**
Fix all linting errors reported by golangci-lint

Closes #6

### CODE REVIEW

File: internal/adapter/in/controller/user_controller_test.go [hunk 1]
```diff
@@ -66,12 +65,13 @@ var _ = Describe("User Controller", func() {
 					Name: userNamespacedName.Namespace,
 				},
 			}
-			k8sClient.Create(ctx, ns)
+			err := k8sClient.Create(ctx, ns)
+			Expect(err).NotTo(HaveOccurred())
```
Comment (kejne) [inline internal/adapter/in/controller/user_controller_test.go:69]: The tests are failing due to that the namespace already exists.
Ignore any errors during namespace creation.

File: internal/adapter/in/controller/account_controller_test.go [hunk 2]
```diff
@@ -83,18 +83,20 @@ var _ = Describe("Account Controller", func() {
 					Name: accountOperatorNamespace,
 				},
 			}
-			k8sClient.Create(ctx, ns)
+			err := k8sClient.Create(ctx, ns)
+			Expect(err).ToNot(HaveOccurred())
```
Comment (kejne) [inline internal/adapter/in/controller/account_controller_test.go:87]: The tests are failing due to that the namespace already exists.
Ignore any errors during namespace creation.

File: internal/adapter/in/controller/account_controller_test.go [hunk 3]
```diff
@@ -83,18 +83,20 @@ var _ = Describe("Account Controller", func() {
 					Name: accountOperatorNamespace,
 				},
 			}
-			k8sClient.Create(ctx, ns)
+			err := k8sClient.Create(ctx, ns)
```
Comment (kejne) [inline internal/adapter/in/controller/account_controller_test.go:86]: The tests are failing due to that the namespace already exists.
Ignore any errors during namespace creation.

File: internal/adapter/in/controller/account_controller_test.go [hunk 4]
```diff
@@ -83,18 +83,20 @@ var _ = Describe("Account Controller", func() {
...
+			Expect(err).ToNot(HaveOccurred())
 
 			ns = &corev1.Namespace{
 				ObjectMeta: metav1.ObjectMeta{
 					Name: accountNamespace,
 				},
 			}
-			k8sClient.Create(ctx, ns)
+			err = k8sClient.Create(ctx, ns)
+			Expect(err).ToNot(HaveOccurred())
```
Comment (kejne) [inline internal/adapter/in/controller/account_controller_test.go:95]: The tests are failing due to that the namespace already exists.
Ignore any errors during namespace creation.

File: internal/adapter/in/controller/user_controller_test.go (hunk 1 above)
Comment (kejne) [inline internal/adapter/in/controller/user_controller_test.go:69]: The tests are failing due to that the namespace already exists.
Ignore any errors during namespace creation.

**Review by kejne — CHANGES_REQUESTED** [review]
Thank you for your contribution @aKjeller!
Looks good :+1: 

The controller tests are however failing due to that the errors from creating the namespaces are now being asserted.

You can run `make test` which will install required binaries for the integration tests.

**Comment by kejne** [comment]
Thanks for your contribution @aKjeller! :tada:
